spring:
  application:
    name: 4k-video
  datasource:
    url: jdbc:mysql://localhost:3306/4k_video
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080